// <auto-generated />
namespace hoangthinh_2080600057.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class taobangmonhoc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taobangmonhoc));
        
        string IMigrationMetadata.Id
        {
            get { return "202303090324179_tao bang mon hoc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
